---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/convert_to_pdf":
    post:
      summary: convert_to_pdf svg
      tags:
      - SVG
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable_content
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: SVG file to convert
              required:
              - file
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
